namespace FINAL_PROGRAMACIÓN_I.Formularios
{
    partial class frmClientes
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmClientes));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.winBg = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.btnImprimir = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.verXNombreCheckbox = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.verTodosCheckbox = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.verXIDCheckbox = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.verXIDTxt = new Bunifu.UI.WinForms.BunifuLabel();
            this.nombreImg = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.idImg = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuSeparator3 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.nombreClienteTxt = new Bunifu.UI.WinForms.BunifuLabel();
            this.idClienteTxt = new Bunifu.UI.WinForms.BunifuLabel();
            this.verXNombreTxt = new Bunifu.UI.WinForms.BunifuLabel();
            this.verTodosTxt = new Bunifu.UI.WinForms.BunifuLabel();
            this.verBtnSep = new Bunifu.UI.WinForms.BunifuSeparator();
            this.verImg = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.verXBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuSeparator2 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.deleteBtnSep = new Bunifu.UI.WinForms.BunifuSeparator();
            this.delImg = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.deleteBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.modBtnSep = new Bunifu.UI.WinForms.BunifuSeparator();
            this.modImg = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.modBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.addBtnSep = new Bunifu.UI.WinForms.BunifuSeparator();
            this.addImg = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.addBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.confirmBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.clientNameInp = new Bunifu.UI.WinForms.BunifuTextBox();
            this.idClientInp = new Bunifu.UI.WinForms.BunifuTextBox();
            this.clientsTable = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.winBg.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.btnImprimir)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nombreImg)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.idImg)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.verImg)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.delImg)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.modImg)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.addImg)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.clientsTable)).BeginInit();
            this.SuspendLayout();
            // 
            // winBg
            // 
            this.winBg.BackColor = System.Drawing.Color.Transparent;
            this.winBg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("winBg.BackgroundImage")));
            this.winBg.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.winBg.BorderRadius = 10;
            this.winBg.Controls.Add(this.btnImprimir);
            this.winBg.Controls.Add(this.verXNombreCheckbox);
            this.winBg.Controls.Add(this.verTodosCheckbox);
            this.winBg.Controls.Add(this.verXIDCheckbox);
            this.winBg.Controls.Add(this.verXIDTxt);
            this.winBg.Controls.Add(this.nombreImg);
            this.winBg.Controls.Add(this.idImg);
            this.winBg.Controls.Add(this.bunifuSeparator3);
            this.winBg.Controls.Add(this.nombreClienteTxt);
            this.winBg.Controls.Add(this.idClienteTxt);
            this.winBg.Controls.Add(this.verXNombreTxt);
            this.winBg.Controls.Add(this.verTodosTxt);
            this.winBg.Controls.Add(this.verBtnSep);
            this.winBg.Controls.Add(this.verImg);
            this.winBg.Controls.Add(this.verXBtn);
            this.winBg.Controls.Add(this.bunifuSeparator2);
            this.winBg.Controls.Add(this.bunifuSeparator1);
            this.winBg.Controls.Add(this.deleteBtnSep);
            this.winBg.Controls.Add(this.delImg);
            this.winBg.Controls.Add(this.deleteBtn);
            this.winBg.Controls.Add(this.modBtnSep);
            this.winBg.Controls.Add(this.modImg);
            this.winBg.Controls.Add(this.modBtn);
            this.winBg.Controls.Add(this.addBtnSep);
            this.winBg.Controls.Add(this.addImg);
            this.winBg.Controls.Add(this.addBtn);
            this.winBg.Controls.Add(this.confirmBtn);
            this.winBg.Controls.Add(this.clientNameInp);
            this.winBg.Controls.Add(this.idClientInp);
            this.winBg.Controls.Add(this.clientsTable);
            this.winBg.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.winBg.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.winBg.GradientTopLeft = System.Drawing.SystemColors.Desktop;
            this.winBg.GradientTopRight = System.Drawing.SystemColors.Desktop;
            this.winBg.Location = new System.Drawing.Point(0, 0);
            this.winBg.Name = "winBg";
            this.winBg.Quality = 10;
            this.winBg.Size = new System.Drawing.Size(1003, 567);
            this.winBg.TabIndex = 2;
            // 
            // btnImprimir
            // 
            this.btnImprimir.AllowFocused = false;
            this.btnImprimir.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnImprimir.AutoSizeHeight = true;
            this.btnImprimir.BorderRadius = 0;
            this.btnImprimir.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnImprimir.Image = ((System.Drawing.Image)(resources.GetObject("btnImprimir.Image")));
            this.btnImprimir.IsCircle = true;
            this.btnImprimir.Location = new System.Drawing.Point(949, 513);
            this.btnImprimir.Name = "btnImprimir";
            this.btnImprimir.Size = new System.Drawing.Size(47, 47);
            this.btnImprimir.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.btnImprimir.TabIndex = 63;
            this.btnImprimir.TabStop = false;
            this.btnImprimir.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            this.btnImprimir.Click += new System.EventHandler(this.btnImprimir_Click);
            // 
            // verXNombreCheckbox
            // 
            this.verXNombreCheckbox.AllowBindingControlAnimation = true;
            this.verXNombreCheckbox.AllowBindingControlColorChanges = false;
            this.verXNombreCheckbox.AllowBindingControlLocation = true;
            this.verXNombreCheckbox.AllowCheckBoxAnimation = false;
            this.verXNombreCheckbox.AllowCheckmarkAnimation = true;
            this.verXNombreCheckbox.AllowOnHoverStates = true;
            this.verXNombreCheckbox.AutoCheck = true;
            this.verXNombreCheckbox.BackColor = System.Drawing.Color.Transparent;
            this.verXNombreCheckbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("verXNombreCheckbox.BackgroundImage")));
            this.verXNombreCheckbox.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.verXNombreCheckbox.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.verXNombreCheckbox.BorderRadius = 12;
            this.verXNombreCheckbox.Checked = false;
            this.verXNombreCheckbox.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Unchecked;
            this.verXNombreCheckbox.Cursor = System.Windows.Forms.Cursors.Default;
            this.verXNombreCheckbox.CustomCheckmarkImage = null;
            this.verXNombreCheckbox.Enabled = false;
            this.verXNombreCheckbox.Location = new System.Drawing.Point(903, 163);
            this.verXNombreCheckbox.MinimumSize = new System.Drawing.Size(17, 17);
            this.verXNombreCheckbox.Name = "verXNombreCheckbox";
            this.verXNombreCheckbox.OnCheck.BorderColor = System.Drawing.Color.DodgerBlue;
            this.verXNombreCheckbox.OnCheck.BorderRadius = 12;
            this.verXNombreCheckbox.OnCheck.BorderThickness = 2;
            this.verXNombreCheckbox.OnCheck.CheckBoxColor = System.Drawing.Color.DodgerBlue;
            this.verXNombreCheckbox.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.verXNombreCheckbox.OnCheck.CheckmarkThickness = 2;
            this.verXNombreCheckbox.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.verXNombreCheckbox.OnDisable.BorderRadius = 12;
            this.verXNombreCheckbox.OnDisable.BorderThickness = 2;
            this.verXNombreCheckbox.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.verXNombreCheckbox.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.verXNombreCheckbox.OnDisable.CheckmarkThickness = 2;
            this.verXNombreCheckbox.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.verXNombreCheckbox.OnHoverChecked.BorderRadius = 12;
            this.verXNombreCheckbox.OnHoverChecked.BorderThickness = 2;
            this.verXNombreCheckbox.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.verXNombreCheckbox.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.verXNombreCheckbox.OnHoverChecked.CheckmarkThickness = 2;
            this.verXNombreCheckbox.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.verXNombreCheckbox.OnHoverUnchecked.BorderRadius = 12;
            this.verXNombreCheckbox.OnHoverUnchecked.BorderThickness = 1;
            this.verXNombreCheckbox.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.verXNombreCheckbox.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.verXNombreCheckbox.OnUncheck.BorderRadius = 12;
            this.verXNombreCheckbox.OnUncheck.BorderThickness = 1;
            this.verXNombreCheckbox.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.verXNombreCheckbox.Size = new System.Drawing.Size(23, 23);
            this.verXNombreCheckbox.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.verXNombreCheckbox.TabIndex = 62;
            this.verXNombreCheckbox.ThreeState = false;
            this.verXNombreCheckbox.ToolTipText = null;
            this.verXNombreCheckbox.CheckedChanged += new System.EventHandler<Bunifu.UI.WinForms.BunifuCheckBox.CheckedChangedEventArgs>(this.verXNombreCheckbox_CheckedChanged);
            // 
            // verTodosCheckbox
            // 
            this.verTodosCheckbox.AllowBindingControlAnimation = true;
            this.verTodosCheckbox.AllowBindingControlColorChanges = false;
            this.verTodosCheckbox.AllowBindingControlLocation = true;
            this.verTodosCheckbox.AllowCheckBoxAnimation = false;
            this.verTodosCheckbox.AllowCheckmarkAnimation = true;
            this.verTodosCheckbox.AllowOnHoverStates = true;
            this.verTodosCheckbox.AutoCheck = true;
            this.verTodosCheckbox.BackColor = System.Drawing.Color.Transparent;
            this.verTodosCheckbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("verTodosCheckbox.BackgroundImage")));
            this.verTodosCheckbox.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.verTodosCheckbox.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.verTodosCheckbox.BorderRadius = 12;
            this.verTodosCheckbox.Checked = false;
            this.verTodosCheckbox.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Unchecked;
            this.verTodosCheckbox.Cursor = System.Windows.Forms.Cursors.Default;
            this.verTodosCheckbox.CustomCheckmarkImage = null;
            this.verTodosCheckbox.Enabled = false;
            this.verTodosCheckbox.Location = new System.Drawing.Point(783, 163);
            this.verTodosCheckbox.MinimumSize = new System.Drawing.Size(17, 17);
            this.verTodosCheckbox.Name = "verTodosCheckbox";
            this.verTodosCheckbox.OnCheck.BorderColor = System.Drawing.Color.DodgerBlue;
            this.verTodosCheckbox.OnCheck.BorderRadius = 12;
            this.verTodosCheckbox.OnCheck.BorderThickness = 2;
            this.verTodosCheckbox.OnCheck.CheckBoxColor = System.Drawing.Color.DodgerBlue;
            this.verTodosCheckbox.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.verTodosCheckbox.OnCheck.CheckmarkThickness = 2;
            this.verTodosCheckbox.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.verTodosCheckbox.OnDisable.BorderRadius = 12;
            this.verTodosCheckbox.OnDisable.BorderThickness = 2;
            this.verTodosCheckbox.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.verTodosCheckbox.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.verTodosCheckbox.OnDisable.CheckmarkThickness = 2;
            this.verTodosCheckbox.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.verTodosCheckbox.OnHoverChecked.BorderRadius = 12;
            this.verTodosCheckbox.OnHoverChecked.BorderThickness = 2;
            this.verTodosCheckbox.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.verTodosCheckbox.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.verTodosCheckbox.OnHoverChecked.CheckmarkThickness = 2;
            this.verTodosCheckbox.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.verTodosCheckbox.OnHoverUnchecked.BorderRadius = 12;
            this.verTodosCheckbox.OnHoverUnchecked.BorderThickness = 1;
            this.verTodosCheckbox.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.verTodosCheckbox.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.verTodosCheckbox.OnUncheck.BorderRadius = 12;
            this.verTodosCheckbox.OnUncheck.BorderThickness = 1;
            this.verTodosCheckbox.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.verTodosCheckbox.Size = new System.Drawing.Size(23, 23);
            this.verTodosCheckbox.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.verTodosCheckbox.TabIndex = 61;
            this.verTodosCheckbox.ThreeState = false;
            this.verTodosCheckbox.ToolTipText = null;
            this.verTodosCheckbox.CheckedChanged += new System.EventHandler<Bunifu.UI.WinForms.BunifuCheckBox.CheckedChangedEventArgs>(this.verTodosCheckbox_CheckedChanged);
            // 
            // verXIDCheckbox
            // 
            this.verXIDCheckbox.AllowBindingControlAnimation = true;
            this.verXIDCheckbox.AllowBindingControlColorChanges = false;
            this.verXIDCheckbox.AllowBindingControlLocation = true;
            this.verXIDCheckbox.AllowCheckBoxAnimation = false;
            this.verXIDCheckbox.AllowCheckmarkAnimation = true;
            this.verXIDCheckbox.AllowOnHoverStates = true;
            this.verXIDCheckbox.AutoCheck = true;
            this.verXIDCheckbox.BackColor = System.Drawing.Color.Transparent;
            this.verXIDCheckbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("verXIDCheckbox.BackgroundImage")));
            this.verXIDCheckbox.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.verXIDCheckbox.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.verXIDCheckbox.BorderRadius = 12;
            this.verXIDCheckbox.Checked = false;
            this.verXIDCheckbox.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Unchecked;
            this.verXIDCheckbox.Cursor = System.Windows.Forms.Cursors.Default;
            this.verXIDCheckbox.CustomCheckmarkImage = null;
            this.verXIDCheckbox.Enabled = false;
            this.verXIDCheckbox.Location = new System.Drawing.Point(681, 163);
            this.verXIDCheckbox.MinimumSize = new System.Drawing.Size(17, 17);
            this.verXIDCheckbox.Name = "verXIDCheckbox";
            this.verXIDCheckbox.OnCheck.BorderColor = System.Drawing.Color.DodgerBlue;
            this.verXIDCheckbox.OnCheck.BorderRadius = 12;
            this.verXIDCheckbox.OnCheck.BorderThickness = 2;
            this.verXIDCheckbox.OnCheck.CheckBoxColor = System.Drawing.Color.DodgerBlue;
            this.verXIDCheckbox.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.verXIDCheckbox.OnCheck.CheckmarkThickness = 2;
            this.verXIDCheckbox.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.verXIDCheckbox.OnDisable.BorderRadius = 12;
            this.verXIDCheckbox.OnDisable.BorderThickness = 2;
            this.verXIDCheckbox.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.verXIDCheckbox.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.verXIDCheckbox.OnDisable.CheckmarkThickness = 2;
            this.verXIDCheckbox.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.verXIDCheckbox.OnHoverChecked.BorderRadius = 12;
            this.verXIDCheckbox.OnHoverChecked.BorderThickness = 2;
            this.verXIDCheckbox.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.verXIDCheckbox.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.verXIDCheckbox.OnHoverChecked.CheckmarkThickness = 2;
            this.verXIDCheckbox.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.verXIDCheckbox.OnHoverUnchecked.BorderRadius = 12;
            this.verXIDCheckbox.OnHoverUnchecked.BorderThickness = 1;
            this.verXIDCheckbox.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.verXIDCheckbox.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.verXIDCheckbox.OnUncheck.BorderRadius = 12;
            this.verXIDCheckbox.OnUncheck.BorderThickness = 1;
            this.verXIDCheckbox.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.verXIDCheckbox.Size = new System.Drawing.Size(23, 23);
            this.verXIDCheckbox.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.verXIDCheckbox.TabIndex = 60;
            this.verXIDCheckbox.ThreeState = false;
            this.verXIDCheckbox.ToolTipText = null;
            this.verXIDCheckbox.CheckedChanged += new System.EventHandler<Bunifu.UI.WinForms.BunifuCheckBox.CheckedChangedEventArgs>(this.verXIDCheckbox_CheckedChanged);
            // 
            // verXIDTxt
            // 
            this.verXIDTxt.AllowParentOverrides = false;
            this.verXIDTxt.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.verXIDTxt.AutoEllipsis = false;
            this.verXIDTxt.Cursor = System.Windows.Forms.Cursors.Default;
            this.verXIDTxt.CursorType = System.Windows.Forms.Cursors.Default;
            this.verXIDTxt.Font = new System.Drawing.Font("Century Gothic", 12F);
            this.verXIDTxt.ForeColor = System.Drawing.Color.White;
            this.verXIDTxt.Location = new System.Drawing.Point(645, 163);
            this.verXIDTxt.Name = "verXIDTxt";
            this.verXIDTxt.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.verXIDTxt.Size = new System.Drawing.Size(17, 21);
            this.verXIDTxt.TabIndex = 45;
            this.verXIDTxt.Text = "ID";
            this.verXIDTxt.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.verXIDTxt.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // nombreImg
            // 
            this.nombreImg.AllowFocused = false;
            this.nombreImg.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.nombreImg.AutoSizeHeight = true;
            this.nombreImg.BorderRadius = 0;
            this.nombreImg.Image = ((System.Drawing.Image)(resources.GetObject("nombreImg.Image")));
            this.nombreImg.IsCircle = false;
            this.nombreImg.Location = new System.Drawing.Point(628, 343);
            this.nombreImg.Name = "nombreImg";
            this.nombreImg.Size = new System.Drawing.Size(128, 128);
            this.nombreImg.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.nombreImg.TabIndex = 42;
            this.nombreImg.TabStop = false;
            this.nombreImg.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // idImg
            // 
            this.idImg.AllowFocused = false;
            this.idImg.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.idImg.AutoSizeHeight = true;
            this.idImg.BorderRadius = 0;
            this.idImg.Image = ((System.Drawing.Image)(resources.GetObject("idImg.Image")));
            this.idImg.IsCircle = true;
            this.idImg.Location = new System.Drawing.Point(628, 206);
            this.idImg.Name = "idImg";
            this.idImg.Size = new System.Drawing.Size(128, 128);
            this.idImg.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.idImg.TabIndex = 41;
            this.idImg.TabStop = false;
            this.idImg.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // bunifuSeparator3
            // 
            this.bunifuSeparator3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator3.BackgroundImage")));
            this.bunifuSeparator3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator3.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator3.LineColor = System.Drawing.Color.White;
            this.bunifuSeparator3.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.DoubleEdgeFaded;
            this.bunifuSeparator3.LineThickness = 1;
            this.bunifuSeparator3.Location = new System.Drawing.Point(571, 190);
            this.bunifuSeparator3.Name = "bunifuSeparator3";
            this.bunifuSeparator3.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator3.Size = new System.Drawing.Size(431, 10);
            this.bunifuSeparator3.TabIndex = 40;
            // 
            // nombreClienteTxt
            // 
            this.nombreClienteTxt.AllowParentOverrides = false;
            this.nombreClienteTxt.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.nombreClienteTxt.AutoEllipsis = false;
            this.nombreClienteTxt.Cursor = System.Windows.Forms.Cursors.Default;
            this.nombreClienteTxt.CursorType = System.Windows.Forms.Cursors.Default;
            this.nombreClienteTxt.Font = new System.Drawing.Font("Century Gothic", 18F);
            this.nombreClienteTxt.ForeColor = System.Drawing.Color.White;
            this.nombreClienteTxt.Location = new System.Drawing.Point(776, 362);
            this.nombreClienteTxt.Name = "nombreClienteTxt";
            this.nombreClienteTxt.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.nombreClienteTxt.Size = new System.Drawing.Size(191, 30);
            this.nombreClienteTxt.TabIndex = 39;
            this.nombreClienteTxt.Text = "Nombre Cliente";
            this.nombreClienteTxt.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.nombreClienteTxt.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // idClienteTxt
            // 
            this.idClienteTxt.AllowParentOverrides = false;
            this.idClienteTxt.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.idClienteTxt.AutoEllipsis = false;
            this.idClienteTxt.Cursor = System.Windows.Forms.Cursors.Default;
            this.idClienteTxt.CursorType = System.Windows.Forms.Cursors.Default;
            this.idClienteTxt.Font = new System.Drawing.Font("Century Gothic", 20F);
            this.idClienteTxt.ForeColor = System.Drawing.Color.White;
            this.idClienteTxt.Location = new System.Drawing.Point(804, 220);
            this.idClienteTxt.Name = "idClienteTxt";
            this.idClienteTxt.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.idClienteTxt.Size = new System.Drawing.Size(129, 33);
            this.idClienteTxt.TabIndex = 38;
            this.idClienteTxt.Text = "ID Cliente";
            this.idClienteTxt.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.idClienteTxt.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // verXNombreTxt
            // 
            this.verXNombreTxt.AllowParentOverrides = false;
            this.verXNombreTxt.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.verXNombreTxt.AutoEllipsis = false;
            this.verXNombreTxt.Cursor = System.Windows.Forms.Cursors.Default;
            this.verXNombreTxt.CursorType = System.Windows.Forms.Cursors.Default;
            this.verXNombreTxt.Font = new System.Drawing.Font("Century Gothic", 12F);
            this.verXNombreTxt.ForeColor = System.Drawing.Color.White;
            this.verXNombreTxt.Location = new System.Drawing.Point(825, 163);
            this.verXNombreTxt.Name = "verXNombreTxt";
            this.verXNombreTxt.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.verXNombreTxt.Size = new System.Drawing.Size(63, 21);
            this.verXNombreTxt.TabIndex = 34;
            this.verXNombreTxt.Text = "Nombre";
            this.verXNombreTxt.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.verXNombreTxt.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // verTodosTxt
            // 
            this.verTodosTxt.AllowParentOverrides = false;
            this.verTodosTxt.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.verTodosTxt.AutoEllipsis = false;
            this.verTodosTxt.Cursor = System.Windows.Forms.Cursors.Default;
            this.verTodosTxt.CursorType = System.Windows.Forms.Cursors.Default;
            this.verTodosTxt.Font = new System.Drawing.Font("Century Gothic", 12F);
            this.verTodosTxt.ForeColor = System.Drawing.Color.White;
            this.verTodosTxt.Location = new System.Drawing.Point(725, 162);
            this.verTodosTxt.Name = "verTodosTxt";
            this.verTodosTxt.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.verTodosTxt.Size = new System.Drawing.Size(45, 21);
            this.verTodosTxt.TabIndex = 33;
            this.verTodosTxt.Text = "Todos";
            this.verTodosTxt.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.verTodosTxt.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // verBtnSep
            // 
            this.verBtnSep.BackColor = System.Drawing.Color.Navy;
            this.verBtnSep.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("verBtnSep.BackgroundImage")));
            this.verBtnSep.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.verBtnSep.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.verBtnSep.LineColor = System.Drawing.Color.Silver;
            this.verBtnSep.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.DoubleEdgeFaded;
            this.verBtnSep.LineThickness = 1;
            this.verBtnSep.Location = new System.Drawing.Point(850, 99);
            this.verBtnSep.Margin = new System.Windows.Forms.Padding(6, 5, 6, 5);
            this.verBtnSep.Name = "verBtnSep";
            this.verBtnSep.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Vertical;
            this.verBtnSep.Size = new System.Drawing.Size(12, 39);
            this.verBtnSep.TabIndex = 31;
            // 
            // verImg
            // 
            this.verImg.AllowFocused = false;
            this.verImg.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.verImg.AutoSizeHeight = true;
            this.verImg.BackColor = System.Drawing.Color.Navy;
            this.verImg.BorderRadius = 19;
            this.verImg.Image = ((System.Drawing.Image)(resources.GetObject("verImg.Image")));
            this.verImg.IsCircle = true;
            this.verImg.Location = new System.Drawing.Point(809, 99);
            this.verImg.Name = "verImg";
            this.verImg.Size = new System.Drawing.Size(38, 38);
            this.verImg.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.verImg.TabIndex = 30;
            this.verImg.TabStop = false;
            this.verImg.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // verXBtn
            // 
            this.verXBtn.AllowAnimations = true;
            this.verXBtn.AllowMouseEffects = true;
            this.verXBtn.AllowToggling = false;
            this.verXBtn.AnimationSpeed = 200;
            this.verXBtn.AutoGenerateColors = false;
            this.verXBtn.AutoRoundBorders = true;
            this.verXBtn.AutoSizeLeftIcon = true;
            this.verXBtn.AutoSizeRightIcon = true;
            this.verXBtn.BackColor = System.Drawing.Color.Transparent;
            this.verXBtn.BackColor1 = System.Drawing.Color.Navy;
            this.verXBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("verXBtn.BackgroundImage")));
            this.verXBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.verXBtn.ButtonText = "Ver";
            this.verXBtn.ButtonTextMarginLeft = 0;
            this.verXBtn.ColorContrastOnClick = 45;
            this.verXBtn.ColorContrastOnHover = 45;
            this.verXBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.verXBtn.CustomizableEdges = borderEdges1;
            this.verXBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.verXBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.verXBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.verXBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.verXBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.verXBtn.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.verXBtn.ForeColor = System.Drawing.Color.White;
            this.verXBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.verXBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.verXBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.verXBtn.IconMarginLeft = 11;
            this.verXBtn.IconPadding = 10;
            this.verXBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.verXBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.verXBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.verXBtn.IconSize = 25;
            this.verXBtn.IdleBorderColor = System.Drawing.Color.Azure;
            this.verXBtn.IdleBorderRadius = 39;
            this.verXBtn.IdleBorderThickness = 1;
            this.verXBtn.IdleFillColor = System.Drawing.Color.Navy;
            this.verXBtn.IdleIconLeftImage = null;
            this.verXBtn.IdleIconRightImage = null;
            this.verXBtn.IndicateFocus = false;
            this.verXBtn.Location = new System.Drawing.Point(795, 98);
            this.verXBtn.Name = "verXBtn";
            this.verXBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.verXBtn.OnDisabledState.BorderRadius = 60;
            this.verXBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.verXBtn.OnDisabledState.BorderThickness = 1;
            this.verXBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.verXBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.verXBtn.OnDisabledState.IconLeftImage = null;
            this.verXBtn.OnDisabledState.IconRightImage = null;
            this.verXBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.verXBtn.onHoverState.BorderRadius = 60;
            this.verXBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.verXBtn.onHoverState.BorderThickness = 1;
            this.verXBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.verXBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.verXBtn.onHoverState.IconLeftImage = null;
            this.verXBtn.onHoverState.IconRightImage = null;
            this.verXBtn.OnIdleState.BorderColor = System.Drawing.Color.Azure;
            this.verXBtn.OnIdleState.BorderRadius = 60;
            this.verXBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.verXBtn.OnIdleState.BorderThickness = 1;
            this.verXBtn.OnIdleState.FillColor = System.Drawing.Color.Navy;
            this.verXBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.verXBtn.OnIdleState.IconLeftImage = null;
            this.verXBtn.OnIdleState.IconRightImage = null;
            this.verXBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.verXBtn.OnPressedState.BorderRadius = 60;
            this.verXBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.verXBtn.OnPressedState.BorderThickness = 1;
            this.verXBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.verXBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.verXBtn.OnPressedState.IconLeftImage = null;
            this.verXBtn.OnPressedState.IconRightImage = null;
            this.verXBtn.Size = new System.Drawing.Size(194, 41);
            this.verXBtn.TabIndex = 29;
            this.verXBtn.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.verXBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.verXBtn.TextMarginLeft = 0;
            this.verXBtn.TextPadding = new System.Windows.Forms.Padding(0, 0, 50, 0);
            this.verXBtn.UseDefaultRadiusAndThickness = true;
            this.verXBtn.Click += new System.EventHandler(this.verXBtn_Click);
            // 
            // bunifuSeparator2
            // 
            this.bunifuSeparator2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator2.BackgroundImage")));
            this.bunifuSeparator2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator2.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator2.LineColor = System.Drawing.Color.White;
            this.bunifuSeparator2.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.DoubleEdgeFaded;
            this.bunifuSeparator2.LineThickness = 1;
            this.bunifuSeparator2.Location = new System.Drawing.Point(760, 399);
            this.bunifuSeparator2.Name = "bunifuSeparator2";
            this.bunifuSeparator2.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator2.Size = new System.Drawing.Size(213, 10);
            this.bunifuSeparator2.TabIndex = 28;
            // 
            // bunifuSeparator1
            // 
            this.bunifuSeparator1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator1.BackgroundImage")));
            this.bunifuSeparator1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator1.LineColor = System.Drawing.Color.White;
            this.bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.DoubleEdgeFaded;
            this.bunifuSeparator1.LineThickness = 1;
            this.bunifuSeparator1.Location = new System.Drawing.Point(761, 257);
            this.bunifuSeparator1.Name = "bunifuSeparator1";
            this.bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator1.Size = new System.Drawing.Size(213, 10);
            this.bunifuSeparator1.TabIndex = 27;
            // 
            // deleteBtnSep
            // 
            this.deleteBtnSep.BackColor = System.Drawing.Color.Navy;
            this.deleteBtnSep.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("deleteBtnSep.BackgroundImage")));
            this.deleteBtnSep.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.deleteBtnSep.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.deleteBtnSep.LineColor = System.Drawing.Color.Silver;
            this.deleteBtnSep.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.DoubleEdgeFaded;
            this.deleteBtnSep.LineThickness = 1;
            this.deleteBtnSep.Location = new System.Drawing.Point(633, 97);
            this.deleteBtnSep.Margin = new System.Windows.Forms.Padding(6, 5, 6, 5);
            this.deleteBtnSep.Name = "deleteBtnSep";
            this.deleteBtnSep.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Vertical;
            this.deleteBtnSep.Size = new System.Drawing.Size(12, 39);
            this.deleteBtnSep.TabIndex = 26;
            // 
            // delImg
            // 
            this.delImg.AllowFocused = false;
            this.delImg.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.delImg.AutoSizeHeight = true;
            this.delImg.BackColor = System.Drawing.Color.Navy;
            this.delImg.BorderRadius = 19;
            this.delImg.Image = ((System.Drawing.Image)(resources.GetObject("delImg.Image")));
            this.delImg.IsCircle = true;
            this.delImg.Location = new System.Drawing.Point(591, 98);
            this.delImg.Name = "delImg";
            this.delImg.Size = new System.Drawing.Size(38, 38);
            this.delImg.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.delImg.TabIndex = 25;
            this.delImg.TabStop = false;
            this.delImg.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // deleteBtn
            // 
            this.deleteBtn.AllowAnimations = true;
            this.deleteBtn.AllowMouseEffects = true;
            this.deleteBtn.AllowToggling = false;
            this.deleteBtn.AnimationSpeed = 200;
            this.deleteBtn.AutoGenerateColors = false;
            this.deleteBtn.AutoRoundBorders = true;
            this.deleteBtn.AutoSizeLeftIcon = true;
            this.deleteBtn.AutoSizeRightIcon = true;
            this.deleteBtn.BackColor = System.Drawing.Color.Transparent;
            this.deleteBtn.BackColor1 = System.Drawing.Color.Navy;
            this.deleteBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("deleteBtn.BackgroundImage")));
            this.deleteBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.deleteBtn.ButtonText = "Eliminar";
            this.deleteBtn.ButtonTextMarginLeft = 0;
            this.deleteBtn.ColorContrastOnClick = 45;
            this.deleteBtn.ColorContrastOnHover = 45;
            this.deleteBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.deleteBtn.CustomizableEdges = borderEdges2;
            this.deleteBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.deleteBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.deleteBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.deleteBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.deleteBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.deleteBtn.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.deleteBtn.ForeColor = System.Drawing.Color.White;
            this.deleteBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.deleteBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.deleteBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.deleteBtn.IconMarginLeft = 11;
            this.deleteBtn.IconPadding = 10;
            this.deleteBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.deleteBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.deleteBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.deleteBtn.IconSize = 25;
            this.deleteBtn.IdleBorderColor = System.Drawing.Color.Azure;
            this.deleteBtn.IdleBorderRadius = 39;
            this.deleteBtn.IdleBorderThickness = 1;
            this.deleteBtn.IdleFillColor = System.Drawing.Color.Navy;
            this.deleteBtn.IdleIconLeftImage = null;
            this.deleteBtn.IdleIconRightImage = null;
            this.deleteBtn.IndicateFocus = false;
            this.deleteBtn.Location = new System.Drawing.Point(578, 96);
            this.deleteBtn.Name = "deleteBtn";
            this.deleteBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.deleteBtn.OnDisabledState.BorderRadius = 60;
            this.deleteBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.deleteBtn.OnDisabledState.BorderThickness = 1;
            this.deleteBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.deleteBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.deleteBtn.OnDisabledState.IconLeftImage = null;
            this.deleteBtn.OnDisabledState.IconRightImage = null;
            this.deleteBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.deleteBtn.onHoverState.BorderRadius = 60;
            this.deleteBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.deleteBtn.onHoverState.BorderThickness = 1;
            this.deleteBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.deleteBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.deleteBtn.onHoverState.IconLeftImage = null;
            this.deleteBtn.onHoverState.IconRightImage = null;
            this.deleteBtn.OnIdleState.BorderColor = System.Drawing.Color.Azure;
            this.deleteBtn.OnIdleState.BorderRadius = 60;
            this.deleteBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.deleteBtn.OnIdleState.BorderThickness = 1;
            this.deleteBtn.OnIdleState.FillColor = System.Drawing.Color.Navy;
            this.deleteBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.deleteBtn.OnIdleState.IconLeftImage = null;
            this.deleteBtn.OnIdleState.IconRightImage = null;
            this.deleteBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.deleteBtn.OnPressedState.BorderRadius = 60;
            this.deleteBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.deleteBtn.OnPressedState.BorderThickness = 1;
            this.deleteBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.deleteBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.deleteBtn.OnPressedState.IconLeftImage = null;
            this.deleteBtn.OnPressedState.IconRightImage = null;
            this.deleteBtn.Size = new System.Drawing.Size(194, 41);
            this.deleteBtn.TabIndex = 24;
            this.deleteBtn.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.deleteBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.deleteBtn.TextMarginLeft = 0;
            this.deleteBtn.TextPadding = new System.Windows.Forms.Padding(0, 0, 30, 0);
            this.deleteBtn.UseDefaultRadiusAndThickness = true;
            this.deleteBtn.Click += new System.EventHandler(this.deleteBtn_Click);
            // 
            // modBtnSep
            // 
            this.modBtnSep.BackColor = System.Drawing.Color.Navy;
            this.modBtnSep.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("modBtnSep.BackgroundImage")));
            this.modBtnSep.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.modBtnSep.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.modBtnSep.LineColor = System.Drawing.Color.Silver;
            this.modBtnSep.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.DoubleEdgeFaded;
            this.modBtnSep.LineThickness = 1;
            this.modBtnSep.Location = new System.Drawing.Point(850, 38);
            this.modBtnSep.Margin = new System.Windows.Forms.Padding(6, 5, 6, 5);
            this.modBtnSep.Name = "modBtnSep";
            this.modBtnSep.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Vertical;
            this.modBtnSep.Size = new System.Drawing.Size(12, 39);
            this.modBtnSep.TabIndex = 23;
            // 
            // modImg
            // 
            this.modImg.AllowFocused = false;
            this.modImg.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.modImg.AutoSizeHeight = true;
            this.modImg.BackColor = System.Drawing.Color.Navy;
            this.modImg.BorderRadius = 19;
            this.modImg.Image = ((System.Drawing.Image)(resources.GetObject("modImg.Image")));
            this.modImg.IsCircle = true;
            this.modImg.Location = new System.Drawing.Point(809, 39);
            this.modImg.Name = "modImg";
            this.modImg.Size = new System.Drawing.Size(38, 38);
            this.modImg.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.modImg.TabIndex = 22;
            this.modImg.TabStop = false;
            this.modImg.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // modBtn
            // 
            this.modBtn.AllowAnimations = true;
            this.modBtn.AllowMouseEffects = true;
            this.modBtn.AllowToggling = false;
            this.modBtn.AnimationSpeed = 200;
            this.modBtn.AutoGenerateColors = false;
            this.modBtn.AutoRoundBorders = true;
            this.modBtn.AutoSizeLeftIcon = true;
            this.modBtn.AutoSizeRightIcon = true;
            this.modBtn.BackColor = System.Drawing.Color.Transparent;
            this.modBtn.BackColor1 = System.Drawing.Color.Navy;
            this.modBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("modBtn.BackgroundImage")));
            this.modBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.modBtn.ButtonText = "Modificar";
            this.modBtn.ButtonTextMarginLeft = 0;
            this.modBtn.ColorContrastOnClick = 45;
            this.modBtn.ColorContrastOnHover = 45;
            this.modBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.modBtn.CustomizableEdges = borderEdges3;
            this.modBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.modBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.modBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.modBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.modBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.modBtn.Font = new System.Drawing.Font("Century Gothic", 11F);
            this.modBtn.ForeColor = System.Drawing.Color.White;
            this.modBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.modBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.modBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.modBtn.IconMarginLeft = 11;
            this.modBtn.IconPadding = 10;
            this.modBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.modBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.modBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.modBtn.IconSize = 25;
            this.modBtn.IdleBorderColor = System.Drawing.Color.Azure;
            this.modBtn.IdleBorderRadius = 39;
            this.modBtn.IdleBorderThickness = 1;
            this.modBtn.IdleFillColor = System.Drawing.Color.Navy;
            this.modBtn.IdleIconLeftImage = null;
            this.modBtn.IdleIconRightImage = null;
            this.modBtn.IndicateFocus = false;
            this.modBtn.Location = new System.Drawing.Point(795, 37);
            this.modBtn.Name = "modBtn";
            this.modBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.modBtn.OnDisabledState.BorderRadius = 60;
            this.modBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.modBtn.OnDisabledState.BorderThickness = 1;
            this.modBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.modBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.modBtn.OnDisabledState.IconLeftImage = null;
            this.modBtn.OnDisabledState.IconRightImage = null;
            this.modBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.modBtn.onHoverState.BorderRadius = 60;
            this.modBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.modBtn.onHoverState.BorderThickness = 1;
            this.modBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.modBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.modBtn.onHoverState.IconLeftImage = null;
            this.modBtn.onHoverState.IconRightImage = null;
            this.modBtn.OnIdleState.BorderColor = System.Drawing.Color.Azure;
            this.modBtn.OnIdleState.BorderRadius = 60;
            this.modBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.modBtn.OnIdleState.BorderThickness = 1;
            this.modBtn.OnIdleState.FillColor = System.Drawing.Color.Navy;
            this.modBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.modBtn.OnIdleState.IconLeftImage = null;
            this.modBtn.OnIdleState.IconRightImage = null;
            this.modBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.modBtn.OnPressedState.BorderRadius = 60;
            this.modBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.modBtn.OnPressedState.BorderThickness = 1;
            this.modBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.modBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.modBtn.OnPressedState.IconLeftImage = null;
            this.modBtn.OnPressedState.IconRightImage = null;
            this.modBtn.Size = new System.Drawing.Size(194, 41);
            this.modBtn.TabIndex = 21;
            this.modBtn.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.modBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.modBtn.TextMarginLeft = 0;
            this.modBtn.TextPadding = new System.Windows.Forms.Padding(0, 0, 28, 0);
            this.modBtn.UseDefaultRadiusAndThickness = true;
            this.modBtn.Click += new System.EventHandler(this.modBtn_Click);
            // 
            // addBtnSep
            // 
            this.addBtnSep.BackColor = System.Drawing.Color.Navy;
            this.addBtnSep.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addBtnSep.BackgroundImage")));
            this.addBtnSep.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.addBtnSep.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.addBtnSep.LineColor = System.Drawing.Color.Silver;
            this.addBtnSep.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.DoubleEdgeFaded;
            this.addBtnSep.LineThickness = 1;
            this.addBtnSep.Location = new System.Drawing.Point(633, 39);
            this.addBtnSep.Margin = new System.Windows.Forms.Padding(6, 5, 6, 5);
            this.addBtnSep.Name = "addBtnSep";
            this.addBtnSep.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Vertical;
            this.addBtnSep.Size = new System.Drawing.Size(12, 39);
            this.addBtnSep.TabIndex = 20;
            // 
            // addImg
            // 
            this.addImg.AllowFocused = false;
            this.addImg.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.addImg.AutoSizeHeight = true;
            this.addImg.BackColor = System.Drawing.Color.Navy;
            this.addImg.BorderRadius = 19;
            this.addImg.Image = ((System.Drawing.Image)(resources.GetObject("addImg.Image")));
            this.addImg.IsCircle = true;
            this.addImg.Location = new System.Drawing.Point(591, 39);
            this.addImg.Name = "addImg";
            this.addImg.Size = new System.Drawing.Size(38, 38);
            this.addImg.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.addImg.TabIndex = 19;
            this.addImg.TabStop = false;
            this.addImg.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // addBtn
            // 
            this.addBtn.AllowAnimations = true;
            this.addBtn.AllowMouseEffects = true;
            this.addBtn.AllowToggling = false;
            this.addBtn.AnimationSpeed = 200;
            this.addBtn.AutoGenerateColors = false;
            this.addBtn.AutoRoundBorders = true;
            this.addBtn.AutoSizeLeftIcon = true;
            this.addBtn.AutoSizeRightIcon = true;
            this.addBtn.BackColor = System.Drawing.Color.Transparent;
            this.addBtn.BackColor1 = System.Drawing.Color.Navy;
            this.addBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addBtn.BackgroundImage")));
            this.addBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addBtn.ButtonText = "Agregar";
            this.addBtn.ButtonTextMarginLeft = 0;
            this.addBtn.ColorContrastOnClick = 45;
            this.addBtn.ColorContrastOnHover = 45;
            this.addBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.addBtn.CustomizableEdges = borderEdges4;
            this.addBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.addBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.addBtn.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.addBtn.ForeColor = System.Drawing.Color.White;
            this.addBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.addBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.addBtn.IconMarginLeft = 11;
            this.addBtn.IconPadding = 10;
            this.addBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.addBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.addBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.addBtn.IconSize = 25;
            this.addBtn.IdleBorderColor = System.Drawing.Color.Azure;
            this.addBtn.IdleBorderRadius = 39;
            this.addBtn.IdleBorderThickness = 1;
            this.addBtn.IdleFillColor = System.Drawing.Color.Navy;
            this.addBtn.IdleIconLeftImage = null;
            this.addBtn.IdleIconRightImage = null;
            this.addBtn.IndicateFocus = false;
            this.addBtn.Location = new System.Drawing.Point(578, 38);
            this.addBtn.Name = "addBtn";
            this.addBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addBtn.OnDisabledState.BorderRadius = 60;
            this.addBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addBtn.OnDisabledState.BorderThickness = 1;
            this.addBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addBtn.OnDisabledState.IconLeftImage = null;
            this.addBtn.OnDisabledState.IconRightImage = null;
            this.addBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addBtn.onHoverState.BorderRadius = 60;
            this.addBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addBtn.onHoverState.BorderThickness = 1;
            this.addBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.addBtn.onHoverState.IconLeftImage = null;
            this.addBtn.onHoverState.IconRightImage = null;
            this.addBtn.OnIdleState.BorderColor = System.Drawing.Color.Azure;
            this.addBtn.OnIdleState.BorderRadius = 60;
            this.addBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addBtn.OnIdleState.BorderThickness = 1;
            this.addBtn.OnIdleState.FillColor = System.Drawing.Color.Navy;
            this.addBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.addBtn.OnIdleState.IconLeftImage = null;
            this.addBtn.OnIdleState.IconRightImage = null;
            this.addBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addBtn.OnPressedState.BorderRadius = 60;
            this.addBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.addBtn.OnPressedState.BorderThickness = 1;
            this.addBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.addBtn.OnPressedState.IconLeftImage = null;
            this.addBtn.OnPressedState.IconRightImage = null;
            this.addBtn.Size = new System.Drawing.Size(194, 41);
            this.addBtn.TabIndex = 18;
            this.addBtn.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.addBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.addBtn.TextMarginLeft = 0;
            this.addBtn.TextPadding = new System.Windows.Forms.Padding(0, 0, 30, 0);
            this.addBtn.UseDefaultRadiusAndThickness = true;
            this.addBtn.Click += new System.EventHandler(this.addBtn_Click);
            // 
            // confirmBtn
            // 
            this.confirmBtn.AllowAnimations = true;
            this.confirmBtn.AllowMouseEffects = true;
            this.confirmBtn.AllowToggling = false;
            this.confirmBtn.AnimationSpeed = 200;
            this.confirmBtn.AutoGenerateColors = false;
            this.confirmBtn.AutoRoundBorders = true;
            this.confirmBtn.AutoSizeLeftIcon = true;
            this.confirmBtn.AutoSizeRightIcon = true;
            this.confirmBtn.BackColor = System.Drawing.Color.Transparent;
            this.confirmBtn.BackColor1 = System.Drawing.Color.Navy;
            this.confirmBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("confirmBtn.BackgroundImage")));
            this.confirmBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.confirmBtn.ButtonText = "-";
            this.confirmBtn.ButtonTextMarginLeft = 0;
            this.confirmBtn.ColorContrastOnClick = 45;
            this.confirmBtn.ColorContrastOnHover = 45;
            this.confirmBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.confirmBtn.CustomizableEdges = borderEdges5;
            this.confirmBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.confirmBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.confirmBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.confirmBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.confirmBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.confirmBtn.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.confirmBtn.ForeColor = System.Drawing.Color.White;
            this.confirmBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.confirmBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.confirmBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.confirmBtn.IconMarginLeft = 11;
            this.confirmBtn.IconPadding = 10;
            this.confirmBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.confirmBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.confirmBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.confirmBtn.IconSize = 25;
            this.confirmBtn.IdleBorderColor = System.Drawing.Color.Azure;
            this.confirmBtn.IdleBorderRadius = 39;
            this.confirmBtn.IdleBorderThickness = 1;
            this.confirmBtn.IdleFillColor = System.Drawing.Color.Navy;
            this.confirmBtn.IdleIconLeftImage = null;
            this.confirmBtn.IdleIconRightImage = null;
            this.confirmBtn.IndicateFocus = false;
            this.confirmBtn.Location = new System.Drawing.Point(654, 489);
            this.confirmBtn.Name = "confirmBtn";
            this.confirmBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.confirmBtn.OnDisabledState.BorderRadius = 60;
            this.confirmBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.confirmBtn.OnDisabledState.BorderThickness = 1;
            this.confirmBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.confirmBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.confirmBtn.OnDisabledState.IconLeftImage = null;
            this.confirmBtn.OnDisabledState.IconRightImage = null;
            this.confirmBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.confirmBtn.onHoverState.BorderRadius = 60;
            this.confirmBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.confirmBtn.onHoverState.BorderThickness = 1;
            this.confirmBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.confirmBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.confirmBtn.onHoverState.IconLeftImage = null;
            this.confirmBtn.onHoverState.IconRightImage = null;
            this.confirmBtn.OnIdleState.BorderColor = System.Drawing.Color.Azure;
            this.confirmBtn.OnIdleState.BorderRadius = 60;
            this.confirmBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.confirmBtn.OnIdleState.BorderThickness = 1;
            this.confirmBtn.OnIdleState.FillColor = System.Drawing.Color.Navy;
            this.confirmBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.confirmBtn.OnIdleState.IconLeftImage = null;
            this.confirmBtn.OnIdleState.IconRightImage = null;
            this.confirmBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.confirmBtn.OnPressedState.BorderRadius = 60;
            this.confirmBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.confirmBtn.OnPressedState.BorderThickness = 1;
            this.confirmBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.confirmBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.confirmBtn.OnPressedState.IconLeftImage = null;
            this.confirmBtn.OnPressedState.IconRightImage = null;
            this.confirmBtn.Size = new System.Drawing.Size(272, 41);
            this.confirmBtn.TabIndex = 17;
            this.confirmBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.confirmBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.confirmBtn.TextMarginLeft = 0;
            this.confirmBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.confirmBtn.UseDefaultRadiusAndThickness = true;
            this.confirmBtn.Click += new System.EventHandler(this.confirmBtn_Click);
            // 
            // clientNameInp
            // 
            this.clientNameInp.AcceptsReturn = false;
            this.clientNameInp.AcceptsTab = true;
            this.clientNameInp.AnimationSpeed = 200;
            this.clientNameInp.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.clientNameInp.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.clientNameInp.AutoSizeHeight = true;
            this.clientNameInp.BackColor = System.Drawing.Color.Transparent;
            this.clientNameInp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("clientNameInp.BackgroundImage")));
            this.clientNameInp.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.clientNameInp.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.clientNameInp.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.clientNameInp.BorderColorIdle = System.Drawing.Color.Silver;
            this.clientNameInp.BorderRadius = 20;
            this.clientNameInp.BorderThickness = 1;
            this.clientNameInp.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.clientNameInp.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.clientNameInp.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.clientNameInp.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.clientNameInp.DefaultText = "";
            this.clientNameInp.FillColor = System.Drawing.Color.White;
            this.clientNameInp.HideSelection = true;
            this.clientNameInp.IconLeft = null;
            this.clientNameInp.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.clientNameInp.IconPadding = 10;
            this.clientNameInp.IconRight = null;
            this.clientNameInp.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.clientNameInp.Lines = new string[0];
            this.clientNameInp.Location = new System.Drawing.Point(761, 415);
            this.clientNameInp.MaxLength = 32767;
            this.clientNameInp.MinimumSize = new System.Drawing.Size(1, 1);
            this.clientNameInp.Modified = false;
            this.clientNameInp.Multiline = false;
            this.clientNameInp.Name = "clientNameInp";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.clientNameInp.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.clientNameInp.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.clientNameInp.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.clientNameInp.OnIdleState = stateProperties4;
            this.clientNameInp.Padding = new System.Windows.Forms.Padding(3);
            this.clientNameInp.PasswordChar = '\0';
            this.clientNameInp.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.clientNameInp.PlaceholderText = "";
            this.clientNameInp.ReadOnly = false;
            this.clientNameInp.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.clientNameInp.SelectedText = "";
            this.clientNameInp.SelectionLength = 0;
            this.clientNameInp.SelectionStart = 0;
            this.clientNameInp.ShortcutsEnabled = true;
            this.clientNameInp.Size = new System.Drawing.Size(215, 38);
            this.clientNameInp.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.clientNameInp.TabIndex = 16;
            this.clientNameInp.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.clientNameInp.TextMarginBottom = 0;
            this.clientNameInp.TextMarginLeft = 3;
            this.clientNameInp.TextMarginTop = 1;
            this.clientNameInp.TextPlaceholder = "";
            this.clientNameInp.UseSystemPasswordChar = false;
            this.clientNameInp.WordWrap = true;
            // 
            // idClientInp
            // 
            this.idClientInp.AcceptsReturn = false;
            this.idClientInp.AcceptsTab = true;
            this.idClientInp.AnimationSpeed = 200;
            this.idClientInp.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.idClientInp.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.idClientInp.AutoSizeHeight = true;
            this.idClientInp.BackColor = System.Drawing.Color.Transparent;
            this.idClientInp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("idClientInp.BackgroundImage")));
            this.idClientInp.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.idClientInp.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.idClientInp.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.idClientInp.BorderColorIdle = System.Drawing.Color.Silver;
            this.idClientInp.BorderRadius = 20;
            this.idClientInp.BorderThickness = 1;
            this.idClientInp.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.idClientInp.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.idClientInp.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.idClientInp.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.idClientInp.DefaultText = "";
            this.idClientInp.FillColor = System.Drawing.Color.White;
            this.idClientInp.HideSelection = true;
            this.idClientInp.IconLeft = null;
            this.idClientInp.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.idClientInp.IconPadding = 10;
            this.idClientInp.IconRight = null;
            this.idClientInp.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.idClientInp.Lines = new string[0];
            this.idClientInp.Location = new System.Drawing.Point(762, 273);
            this.idClientInp.MaxLength = 32767;
            this.idClientInp.MinimumSize = new System.Drawing.Size(1, 1);
            this.idClientInp.Modified = false;
            this.idClientInp.Multiline = false;
            this.idClientInp.Name = "idClientInp";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idClientInp.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.idClientInp.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idClientInp.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idClientInp.OnIdleState = stateProperties8;
            this.idClientInp.Padding = new System.Windows.Forms.Padding(3);
            this.idClientInp.PasswordChar = '\0';
            this.idClientInp.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.idClientInp.PlaceholderText = "";
            this.idClientInp.ReadOnly = false;
            this.idClientInp.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.idClientInp.SelectedText = "";
            this.idClientInp.SelectionLength = 0;
            this.idClientInp.SelectionStart = 0;
            this.idClientInp.ShortcutsEnabled = true;
            this.idClientInp.Size = new System.Drawing.Size(215, 38);
            this.idClientInp.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.idClientInp.TabIndex = 15;
            this.idClientInp.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.idClientInp.TextMarginBottom = 0;
            this.idClientInp.TextMarginLeft = 3;
            this.idClientInp.TextMarginTop = 1;
            this.idClientInp.TextPlaceholder = "";
            this.idClientInp.UseSystemPasswordChar = false;
            this.idClientInp.WordWrap = true;
            // 
            // clientsTable
            // 
            this.clientsTable.AllowCustomTheming = false;
            this.clientsTable.AllowUserToAddRows = false;
            this.clientsTable.AllowUserToDeleteRows = false;
            this.clientsTable.AllowUserToResizeColumns = false;
            this.clientsTable.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(223)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.clientsTable.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.clientsTable.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.clientsTable.BackgroundColor = System.Drawing.Color.Black;
            this.clientsTable.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.clientsTable.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleVertical;
            this.clientsTable.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.Navy;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(102)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.clientsTable.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.clientsTable.ColumnHeadersHeight = 40;
            this.clientsTable.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(223)))));
            this.clientsTable.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.clientsTable.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.clientsTable.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(102)))), ((int)(((byte)(178)))));
            this.clientsTable.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
            this.clientsTable.CurrentTheme.BackColor = System.Drawing.Color.Navy;
            this.clientsTable.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(178)))), ((int)(((byte)(216)))));
            this.clientsTable.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.Navy;
            this.clientsTable.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.clientsTable.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.clientsTable.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(102)))));
            this.clientsTable.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.clientsTable.CurrentTheme.Name = null;
            this.clientsTable.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(229)))));
            this.clientsTable.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.clientsTable.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.clientsTable.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(102)))), ((int)(((byte)(178)))));
            this.clientsTable.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(229)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(102)))), ((int)(((byte)(178)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.clientsTable.DefaultCellStyle = dataGridViewCellStyle3;
            this.clientsTable.Dock = System.Windows.Forms.DockStyle.Left;
            this.clientsTable.EnableHeadersVisualStyles = false;
            this.clientsTable.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(178)))), ((int)(((byte)(216)))));
            this.clientsTable.HeaderBackColor = System.Drawing.Color.Navy;
            this.clientsTable.HeaderBgColor = System.Drawing.Color.Empty;
            this.clientsTable.HeaderForeColor = System.Drawing.Color.White;
            this.clientsTable.Location = new System.Drawing.Point(0, 0);
            this.clientsTable.MultiSelect = false;
            this.clientsTable.Name = "clientsTable";
            this.clientsTable.ReadOnly = true;
            this.clientsTable.RowHeadersVisible = false;
            this.clientsTable.RowHeadersWidth = 62;
            this.clientsTable.RowTemplate.Height = 40;
            this.clientsTable.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.CellSelect;
            this.clientsTable.Size = new System.Drawing.Size(569, 567);
            this.clientsTable.TabIndex = 0;
            this.clientsTable.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Navy;
            this.clientsTable.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.clientsTable_CellClick);
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = true;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = true;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // frmClientes
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Black;
            this.ClientSize = new System.Drawing.Size(1003, 567);
            this.Controls.Add(this.winBg);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "frmClientes";
            this.Text = "Clientes";
            this.Load += new System.EventHandler(this.frmClientes_Load);
            this.winBg.ResumeLayout(false);
            this.winBg.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.btnImprimir)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nombreImg)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.idImg)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.verImg)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.delImg)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.modImg)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.addImg)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.clientsTable)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGradientPanel winBg;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private Bunifu.UI.WinForms.BunifuDataGridView clientsTable;
        private Bunifu.UI.WinForms.BunifuTextBox idClientInp;
        private Bunifu.UI.WinForms.BunifuTextBox clientNameInp;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 confirmBtn;
        private Bunifu.UI.WinForms.BunifuSeparator deleteBtnSep;
        private Bunifu.UI.WinForms.BunifuPictureBox delImg;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 deleteBtn;
        private Bunifu.UI.WinForms.BunifuSeparator modBtnSep;
        private Bunifu.UI.WinForms.BunifuPictureBox modImg;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 modBtn;
        private Bunifu.UI.WinForms.BunifuSeparator addBtnSep;
        private Bunifu.UI.WinForms.BunifuPictureBox addImg;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 addBtn;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator2;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
        private Bunifu.UI.WinForms.BunifuSeparator verBtnSep;
        private Bunifu.UI.WinForms.BunifuPictureBox verImg;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 verXBtn;
        private Bunifu.UI.WinForms.BunifuLabel verTodosTxt;
        private Bunifu.UI.WinForms.BunifuLabel verXNombreTxt;
        private Bunifu.UI.WinForms.BunifuLabel idClienteTxt;
        private Bunifu.UI.WinForms.BunifuLabel nombreClienteTxt;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator3;
        private Bunifu.UI.WinForms.BunifuPictureBox nombreImg;
        private Bunifu.UI.WinForms.BunifuPictureBox idImg;
        private Bunifu.UI.WinForms.BunifuLabel verXIDTxt;
        private Bunifu.UI.WinForms.BunifuCheckBox verXIDCheckbox;
        private Bunifu.UI.WinForms.BunifuCheckBox verXNombreCheckbox;
        private Bunifu.UI.WinForms.BunifuCheckBox verTodosCheckbox;
        private Bunifu.UI.WinForms.BunifuPictureBox btnImprimir;
    }
}